### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME on Windows

### ISSUE THREAD

**Issue by mraf** [jeasx/jeasx#5]
Hi 

followed https://www.jeasx.dev/quickstart 

created project but on Windows it's creating this error 

`{"statusCode":500,"code":"ERR_UNSUPPORTED_ESM_URL_SCHEME","error":"Internal Server Error","message":"Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'"}`

OS: Windows 11
Node version: v20.10.0

looks similar to issue on node [https://github.com/nodejs/node/issues/31710](https://github.com/nodejs/node/issues/31710)

**Comment by jablonski** [comment]
Thank you very much.

I don't have a working Windows installation (and never tested jeasx on Windows), but the linked GitHub issue makes totally sense. I'm going to setup an windows environment and going to fix this issue.

**Comment by mraf** [comment]
First of all I should say congratulations on the launch! This looks awesome and seems to be very powerful and also so quick!

Feels like fresh approach to the development 🚀 

I'm also not using Windows for normal work but I had in hand when found jeasx.
Maybe in the end it's not that bad as first issue so we will know that can work on any system.

**Comment by jablonski** [comment]
I could reproduce the issue on Windows. A fix is published in jeasx 0.3.4. Works for me now on Windows 10, maybe you can try it and report if it works for you too?

https://github.com/jeasx/jeasx/commit/3bb7f948fd33016da8749cf9e2dcbadffb232595

**Comment by mraf** [comment]
All working fine now. Thank you!
